version: '3.8'

services:
  zorgmate-db:
    image: postgres:14
    container_name: zorgmate-db
    environment:
      POSTGRES_DB: zorgmate
      POSTGRES_USER: zorg
      POSTGRES_PASSWORD: 123
    volumes:
      - zorgmate-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  zorgmate-app:
    build: .
    container_name: zorgmate
    depends_on:
      - zorgmate-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://zorgmate-db:5432/zorgmate
      SPRING_DATASOURCE_USERNAME: zorg
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_PROFILES_ACTIVE: default

volumes:
  zorgmate-pgdata:
