version: '3.8'

services:
  zorgmate-app:
    image: fays21/zorgmate:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://zorgmate-db:5432/zorgmate
      SPRING_DATASOURCE_USERNAME: zorguser
      SPRING_DATASOURCE_PASSWORD: zorgpass
    depends_on:
      - zorgmate-db

  zorgmate-db:
    image: postgres:14
    container_name: zorgmate-db
    restart: always
    environment:
      POSTGRES_DB: zorgmate
      POSTGRES_USER: zorguser
      POSTGRES_PASSWORD: zorgpass
    volumes:
      - zorgmate-data:/var/lib/postgresql/data

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_INCLUDE_RESTARTING: "true"

volumes:
  zorgmate-data:
